# Generated by Django 3.1.3 on 2022-08-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_reviews_options_remove_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
